title = "100j4m0"

[info]
name = "100 jobs 4 machines example 0"

[files]
data = "../data/100j4m0.csv"
processing_times = "../data/100j4m0.csv"

[problem_data]
index_cols = ["id"]
grouping_cols = ["gr1"]
conflicting_machines = [
  [2, 3]
]

[algorithm_config]
beam_witdh = 5
