title = "20j20m_0"

[info]
name = "20 jobs 20 machines example 0"

[files]
data = "../data/20j20m0.csv"
processing_times = "../data/20j20m0.csv"

[problem_data]
index_cols = ["id"]
grouping_cols = ["gr"]
conflicting_machines = [
  [1, 2],
  [5, 8],
  [16, 19]
]

[algorithm_config]
beam_witdh = 5
