BASE_URL = r'https://localhost:44320/Operations'
DEFAULT_ALGORITHM = 'insertion_beam'
DEFAULT_OBJECTIVE = 'cmax'
DEFAULT_BEAM_WIDTH = 5
PRINT_RESPONSES = True
SHOW_CONFLICT_GRAPH = False
SHOW_RESULT_SCHEDULE_GRAPH = False
SHOW_GANTT = True
